### ISSUE TITLE
TypeError: 'property' object is not callable

### ISSUE THREAD

**Issue by thinkoco** [anirudhSK/drmt#3]
Hi, I get some errors here when running it.
```
Traceback (most recent call last):
  File "drmt.py", line 267, in <module>
    G.create_dag(input_spec.nodes, input_spec.edges, latency_spec)
  File "/home/knat/Documents/Venus/other/DRMT/drmt/schedule_dag.py", line 42, in create_dag
    for u in self.nodes():
  File "/home/knat/Documents/Venus/other/DRMT/drmt/schedule_dag.py", line 126, in nodes
    for (u, d) in nx.DiGraph.nodes(self, data=True):
TypeError: 'property' object is not callable
Command exited with non-zero status 1
```
It may be the runtime issue. and  I want to know which versions of the Python , Gurobi and networkx   did you  used.
Any help will be appreciated.

**Comment by shayvar** [comment]
Hi,

We used Python 2.7. For Gurobi, we used 7.0.1.

I don't recall the networkx version. I believe I was 2.0 or maybe the older
1.11.

**Comment by thinkoco** [comment]
@shayvar Thank you, I will try it again.
